### ISSUE TITLE
Samples don't work for latest Azure.WebJobs.* Nuget packages for `Producer` project

### ISSUE THREAD

**Issue by sumitkm** [Azure-Samples/durable-functions-producer-consumer#17]
Repro
- Clone Repo, open solution, Rebuild. All OK
- Select `Producer` project and Update Nuget Packages
- Rebuild, Build fails with 30 errors.

![image](https://user-images.githubusercontent.com/578882/145390608-851bb8ac-d54b-438b-b5e3-2275256b1442.png)

**Comment by sumitkm** [comment]
Bump! This is blocking upgrade to latest `Micrsofot.Azure.Webjobs.Extensions.ServiceBus`, @brandom-msft any pointers?

**Comment by brandom-msft** [comment]
I think you're looking for @brandonh-msft

**Comment by brandonh-msft** [comment]
What is in the new SB extension that you require?

**Comment by sumitkm** [comment]
Basically we have Timer Trigger functions that consume a `ServiceBus` and put messages on the bus, for example as follows (using Microsoft.Azure.WebJobs.Extensions.ServiceBus v4.x.y)
```
public static class ExchangeRatesRefresh
    {
        [FunctionName("ExchangeRatesRefresh")]
        public static void Run([TimerTrigger("%my_TimerCronExchangeRatesRefresh%", RunOnStartup = false, UseMonitor = false)] TimerInfo myTimer,
            [ServiceBus(My.Function.Settings.Settings.ScheduledTaskQueue, 
                Connection = "my_ServiceBus", EntityType = EntityType.Queue)] out Message sbQueue,
            ILogger log)
           
        {
            var functionName = "ExchangeRatesRefresh";
            log.LogInformation($"Azure Timer trigger function {functionName} called at: {DateTime.UtcNow}");


            var message = new ScheduledTask { TaskType = ScheduledTaskType.ExchangeRatesRefresh };
            var payload = JsonConvert.SerializeObject(message);
            var body = Encoding.UTF8.GetBytes(payload);
            var msg = new Message(body);
            msg.UserProperties.Add("Serializer", "json");
            sbQueue = msg;
        }
 ```
The new  `Microsoft.Azure.WebJobs.Extensions.ServiceBus` (v5.2.0) simply breaks the above code, including the `[ServiceBus(...)]` attribute. So I came looking for examples and the closest I found was the durable functions sample.
 
However I have now found a sample on [SO](https://stackoverflow.com/a/60613788) which roughly changes the above to 
 ```
    public static class ExchangeRatesRefresh
    {
        [FunctionName("ExchangeRatesRefresh")]
        [return: ServiceBus(My.Function.Settings.Settings.ScheduledTaskQueue, Connection = "my_MyBus")]
        public static async Task Run(
            [TimerTrigger("%my_TimerCronExchangeRatesRefresh%", RunOnStartup = false, UseMonitor = false)] TimerInfo myTimer,
            [ServiceBus(My.Function.Settings.Settings.ScheduledTaskQueue, Connection = "my_MyBus")] MessageSender sbQueue,
            ILogger log)
           
        {
            var functionName = "ExchangeRatesRefresh";
            log.LogInformation($"Azure Timer trigger function {functionName} called at: {DateTime.UtcNow}");


            var message = new ScheduledTask { TaskType = ScheduledTaskType.ExchangeRatesRefresh };
            var payload = JsonConvert.SerializeObject(message);
            var body = Encoding.UTF8.GetBytes(payload);
            var msg = new Message(body);
            msg.UserProperties.Add("Serializer", "json");
            await sbQueue.SendAsync(msg).ConfigureAwait(false);
        }
    }
 ```
It compiles but not sure if the above is correct, in middle of a massive `net6.0` upgrade so will only know once it is all done.
 
I am just blindly following code snippets here. Any pointers to documentation would be mighty helpful. 
 
Update 1: On further reading [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-output?tabs=csharp) I guess I don't need the `[return: ServiceBus(My.Function.Settings.Settings.ScheduledTaskQueue, Connection = "my_MyBus")]` attribute in my case. But I could be wrong. I can't find a sample that injects a `ServiceBus` instance into the function.

**Comment by sumitkm** [comment]
Okay, on some further investigation it turns out to be a storm in a teacup. The Enum `EntityType` is now called `ServiceBusEntityType`. I don't have to make any other changes to my existing code. My issue is resolved. 

The code in this repo however is a different issue :D

**Comment by brandonh-msft** [comment]
Since the code in the repo functions out-of-the-box for its target use case, I'm considering this a non-issue.

**Comment by sumitkm** [comment]
Is the code for the latest sdk somewhere else? The code in the repo still doesn't compile once we update Nuget packages. So 'works for target usecase' is subject to whether this is the definitive samples repo for Azure Functions.

**Comment by brandonh-msft** [comment]
it is the definitive samples repo; the sample still functions for its purpose. but we're always happy to accept PRs that update things to the latest if people deem that important.

**Comment by sumitkm** [comment]
:-p I get the hint... I'll see if I can wrap my head around it.
