### ISSUE TITLE
Compiling issues when Microsoft.Azure.WebJobs.Extensions.DurableTask updated to 2.0

### ISSUE THREAD

**Issue by agowdamsft** [Azure-Samples/durable-functions-producer-consumer#3]
You will start seeing issues with Durable Functions Orchestrations reference when you update the nuget package to 2.0 (latest stable release). Ideally this sample should be updated to use the latest 2.0 release of Microsoft.Azure.WebJobs.Extensions.DurableTask

**Comment by brandonh-msft** [comment]
This is resolved in [the new `v2x` branch](https://github.com/Azure-Samples/durable-functions-producer-consumer/tree/v2x) of the sample. Thanks!
