### ISSUE TITLE
deploy.ps1 fails to create event hub

### ISSUE THREAD

**Issue by aautere** [Azure-Samples/durable-functions-producer-consumer#8]
### Minimal steps to reproduce
Run deploy.ps1 with params

### Any log messages given by the failure
deploy.ps1:70
Line |
  70 |  … loyResult = New-AzResourceGroupDeployment -ResourceGroupName $resourc …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 13.48.41 - Resource Microsoft.EventHub/namespaces 'ehkfsrwmg6n7u2t2' failed with message
     | '{   "error": {     "message": "Cannot set MaximumThroughputUnits property if AutoInflate
     | is not enabled. CorrelationId: ac3085a0-4224-4f73-ae54-50d7c400a3e5",     "code":
     | "BadRequest"   } }'

### Expected/desired behavior
Should pass

### OS and Version?
Win 10
PowerShell 7.0.0
Azure PS 3.7.

**Comment by brandonh-msft** [comment]
I've been testing EH extensively lately and believe this to be fixed.
